### ISSUE TITLE
Types seems to be broken with composition-api v0.6.3

### ISSUE THREAD

**Issue by vmihailenco** [antfu/vueuse#88]
I get errors like

```
ERROR in node_modules/@vueuse/core/index.d.ts(1,21):
1:21 Cannot find module '@vue/composition-api/dist/reactivity/ref' or its corresponding type declarations.
  > 1 | import { Ref } from '@vue/composition-api/dist/reactivity/ref';
```

Same code works with composition-api v0.6.1

**Comment by antfu** [comment]
Should be fixed in 2.0.34. Thanks!
